server:
  port: 8082

spring:
  application:
    name: NativeCodeDistributionService
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: "local"
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    codeNotificationTopic: "code-notification-topic"
    codeNotificationGroupId: "code-notification-group"